# Generated by Django 4.1.7 on 2023-03-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='yaer',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Год выпуска'),
            preserve_default=False,
        ),
    ]
