# Generated by Django 4.1.7 on 2023-04-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_specialmarks_periodsownership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='yaer',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rubben_location',
        ),
        migrations.RemoveField(
            model_name='periodsownership',
            name='actual',
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default=1, max_length=100, verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='rudder_location',
            field=models.CharField(default=1, max_length=100, verbose_name='Расположение руля'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.PositiveSmallIntegerField(verbose_name='Объем двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=200, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='periodsownership',
            name='before_date',
            field=models.DateField(blank=True, null=True, verbose_name='До'),
        ),
        migrations.AlterField(
            model_name='periodsownership',
            name='from_date',
            field=models.DateField(auto_now_add=True, verbose_name='От'),
        ),
    ]
